In [1]:
import h5py
from PIL import Image

fileName = 'data.h5'
numOfSamples = 17568
with h5py.File(fileName, "w") as out:
    out.create_dataset("X", (numOfSamples, 256, 256, 3), dtype='u1')
    out.create_dataset("Y", (numOfSamples, 1, 1), dtype='u1')       

In [4]:
from glob import glob
import cv2

imagePatches = glob('chest_xray/**/**/*.jpeg', recursive=True)
print(len(imagePatches))

#pattern_normal = '*NORMAL*'
#pattern_bacteria = '*_bacteria_*'
#pattern_virus = '*_virus_*'

#normal = fnmatch.filter(imagePatches, pattern_normal)
#bacteria = fnmatch.filter(imagePatches, pattern_bacteria)
#virus = fnmatch.filter(imagePatches, pattern_virus)
x = []
y = []
for img in imagePatches:
    full_size_image = cv2.imread(img)
    im = cv2.resize(full_size_image, (256, 256), interpolation=cv2.INTER_CUBIC)
    x.append(im)
    if "NORMAL" in img:
        y.append(0)
    elif "bacteria" in img:
        y.append(1)
    elif "virus" in img:
        y.append(1)
    else:
        #break
        print('no class')

17568


In [24]:
import numpy as np

for i in range(len(x)):
    with h5py.File(fileName, "a") as out:
        out['X'+str(i)] = np.asarray(x[i])
        out['Y'+str(i)] = y[i]

In [20]:
with h5py.File(fileName, "a") as out:      # X_train_1.jpg is 256 x 256 RGB image
    i = np.asarray(out['X_train3'])
print(i)

[[[ 1  1  1]
  [12 12 12]
  [ 7  7  7]
  ...
  [66 66 66]
  [70 70 70]
  [71 71 71]]

 [[ 0  0  0]
  [13 13 13]
  [ 9  9  9]
  ...
  [65 65 65]
  [64 64 64]
  [63 63 63]]

 [[ 0  0  0]
  [12 12 12]
  [ 8  8  8]
  ...
  [60 60 60]
  [58 58 58]
  [57 57 57]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [24]:
dic = {'property_id': '23711069', 'name': 'Nice JBR Beach Apartment with Dream Sea View', 'address': {'line_1': 'Dorra Bay', 'line_2': 'Dubai Marina', 'city': 'Dubai', 'country_code': 'AE'}, 'ratings': {'property': {'rating': '0.0', 'type': 'Alternate'}}, 'location': {'coordinates': {'latitude': 25.071477, 'longitude': 55.128789}}, 'phone': '971-55-9609739', 'fax': '971-55-9609739', 'category': {'id': 16, 'name': 'Apartment'}, 'rank': 328213, 'business_model': {'expedia_collect': True, 'property_collect': False}, 'checkin': {'begin_time': '3:00 PM', 'instructions': 'Extra-person charges may apply and vary depending on property policy. <br />Government-issued photo identification and a credit card, debit card, or cash deposit are required at check-in for incidental charges. <br />Special requests are subject to availability upon check-in and may incur additional charges. Special requests cannot be guaranteed. <ul> Guests must contact this property in advance to reserve cribs/infant beds.  Please note that cultural norms and guest policies may differ by country and by property. The policies listed are provided by the property. </ul>', 'special_instructions': "There is no front desk at this property. This property doesn't offer after-hours check-in. Guests arriving late won't be able to check in until the next morning. To make arrangements for check-in please contact the property at least 24 hours before arrival using the information on the booking confirmation.  Guests must email a copy of their government-issued identification or passport to the property 24 Hours in advance of arrival. For more details, please contact the office using the information on the reservation confirmation received after booking.", 'min_age': '18'}, 'checkout': {'time': '11:00 AM'}, 'fees': {'mandatory': "<p>You'll be asked to pay the following charges at the property:</p> <ul><li>Deposit: AED 3000 per stay</li><li>A tax is imposed by the city: AED 30 per accommodation, per night</li><li>Cleaning fees vary based on length of stay</li> A tourism fee is imposed by the city and collected at the property. The fee is AED 10 for the first bedroom per night, and increases by AED 10 per night for each additional bedroom. </ul> <p>We have included all charges provided to us by the property. However, charges can vary, for example, based on length of stay or the room you book. </p>"}, 'policies': {'know_before_you_go': "<ul>  <li>This property's policy is to refuse certain bookings for the purpose of group events or parties, including pre-wedding stag/bachelor and hen/bachelorette parties. </li><li>Only registered guests are allowed in the guestrooms. </li>  </ul>"}, 'attributes': {'pets': {'2050': {'id': 2050, 'name': 'Pets not allowed'}}, 'general': {'2544': {'id': 2544, 'name': 'No rollaway/extra beds available'}}}, 'amenities': {'8': {'id': 8, 'name': 'Elevator'}, '24': {'id': 24, 'name': 'Outdoor pool'}, '9': {'id': 9, 'name': 'Fitness facilities'}, '2137': {'id': 2137, 'name': 'Smoke-free property'}, '3861': {'id': 3861, 'name': 'Free self parking'}}, 'images': [{'caption': 'Featured Image', 'hero_image': True, 'category': 3, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_z.jpg'}}}, {'caption': 'Room', 'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_z.jpg'}}}, {'caption': 'In-Room Dining', 'hero_image': False, 'category': 22001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_z.jpg'}}}, {'caption': 'Private Kitchen', 'hero_image': False, 'category': 22002, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_z.jpg'}}}, {'caption': 'Private Kitchen', 'hero_image': False, 'category': 22002, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_z.jpg'}}}, {'caption': 'Private Kitchen', 'hero_image': False, 'category': 22002, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_z.jpg'}}}, {'caption': 'Living Area', 'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_z.jpg'}}}, {'caption': 'Living Area', 'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_z.jpg'}}}, {'caption': 'Living Area', 'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_z.jpg'}}}, {'caption': 'Living Area', 'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_z.jpg'}}}, {'caption': 'Living Area', 'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_z.jpg'}}}, {'caption': 'Balcony', 'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_z.jpg'}}}, {'caption': 'Balcony', 'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_z.jpg'}}}, {'caption': 'Balcony', 'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_z.jpg'}}}, {'caption': 'Balcony', 'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_z.jpg'}}}, {'caption': 'Room Amenity', 'hero_image': False, 'category': 22009, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_z.jpg'}}}, {'caption': 'View from Room', 'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_z.jpg'}}}, {'caption': 'View from Room', 'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_z.jpg'}}}, {'caption': 'View from Room', 'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_z.jpg'}}}, {'caption': 'View from Room', 'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_z.jpg'}}}, {'caption': 'Bathroom', 'hero_image': False, 'category': 23000, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_z.jpg'}}}, {'caption': 'Bathroom Sink', 'hero_image': False, 'category': 23003, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_z.jpg'}}}, {'caption': 'Hallway', 'hero_image': False, 'category': 83007, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2a70961e_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2a70961e_t.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2a70961e_z.jpg'}}}], 'onsite_payments': {'currency': 'AED', 'types': {'184': {'id': 184, 'name': 'Mastercard'}, '171': {'id': 171, 'name': 'American Express'}, '189': {'id': 189, 'name': 'Visa'}}}, 'rooms': {'216604282': {'id': '216604282', 'name': 'Apartment, 3 Bedrooms', 'descriptions': {'overview': '<p><strong>3 King Beds</strong></p><p><b>Layout</b> - 3 bedrooms </p><p><b>Internet</b> - Free WiFi </p><p><b>Entertainment</b> - LED television with cable channels</p><p><b>Food & Drink</b> - Kitchen with refrigerator, stovetop, microwave, and cookware/dishware</p><p><b>Bathroom</b> - Private bathroom, shower/tub combination, free toiletries, and a hair dryer</p><p><b>Practical</b> - Washing machine, twin sofa bed, and iron/ironing board (on request); free cribs/infant beds available on request</p><p><b>Comfort</b> - Air conditioning</p><p><b>Need to Know</b> - Limited housekeeping</p><p>Non-Smoking</p>&nbsp;'}, 'amenities': {'6176': {'id': 6176, 'name': 'Non-Smoking'}, '1': {'id': 1, 'name': 'Air conditioning'}, '130': {'id': 130, 'name': 'Refrigerator'}, '2403': {'id': 2403, 'name': 'Free WiFi'}, '6147': {'id': 6147, 'name': 'LED TV'}, '2183': {'id': 2183, 'name': 'Shower/tub combination'}, '2055': {'id': 2055, 'name': 'Iron/ironing board (on request)'}, '4008': {'id': 4008, 'name': 'Housekeeping - once per stay'}, '1073743880': {'id': 1073743880, 'name': 'Fan'}, '2058': {'id': 2058, 'name': 'Microwave'}, '2059': {'id': 2059, 'name': 'Cookware, dishware, and utensils'}, '141': {'id': 141, 'name': 'Private bathroom'}, '2381': {'id': 2381, 'name': 'Stovetop'}, '2158': {'id': 2158, 'name': 'Kitchen'}, '143': {'id': 143, 'name': 'Free toiletries'}, '1073743311': {'id': 1073743311, 'name': 'Washing machine'}, '144': {'id': 144, 'name': 'Hair dryer'}, '1073742676': {'id': 1073742676, 'name': 'Limited housekeeping'}, '4951': {'id': 4951, 'name': 'Free cribs/infant beds'}, '1073743289': {'id': 1073743289, 'name': 'Electric kettle'}, '2398': {'id': 2398, 'name': 'Cable TV service'}}, 'images': [{'hero_image': True, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/00dbfd03_z.jpg'}}}, {'hero_image': False, 'category': 3, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f0a5daea_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/3b540cfa_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d25c06e6_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a47b76ce_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b415247_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/0f6f9746_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/eb366acb_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f4ba6ab1_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/041dd7fa_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/62113aeb_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/52cd58c6_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b1146e9f_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/9c88ac2b_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b730a8fc_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f1726ca9_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4e70ad34_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/894d894c_z.jpg'}}}, {'hero_image': False, 'category': 21001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/f66f27bc_z.jpg'}}}, {'hero_image': False, 'category': 22001, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/4f098ce5_z.jpg'}}}, {'hero_image': False, 'category': 22002, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/a5895e15_z.jpg'}}}, {'hero_image': False, 'category': 22002, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c57c0528_z.jpg'}}}, {'hero_image': False, 'category': 22002, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/502522cc_z.jpg'}}}, {'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/82033e6b_z.jpg'}}}, {'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2688fba7_z.jpg'}}}, {'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/89642c3f_z.jpg'}}}, {'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/153413d2_z.jpg'}}}, {'hero_image': False, 'category': 22005, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/e1ca723d_z.jpg'}}}, {'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/41b37ee0_z.jpg'}}}, {'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/5b8a6157_z.jpg'}}}, {'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ed4096f1_z.jpg'}}}, {'hero_image': False, 'category': 22008, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/c5d7d1b5_z.jpg'}}}, {'hero_image': False, 'category': 22009, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/b974de99_z.jpg'}}}, {'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/7ed3f231_z.jpg'}}}, {'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/d233548d_z.jpg'}}}, {'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/08b396c4_z.jpg'}}}, {'hero_image': False, 'category': 22013, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/ec4f4c52_z.jpg'}}}, {'hero_image': False, 'category': 23000, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/2b524ec4_z.jpg'}}}, {'hero_image': False, 'category': 23003, 'links': {'350px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_b.jpg'}, '70px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_t.jpg'}, '200px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_s.jpg'}, '1000px': {'method': 'GET', 'href': 'https://i.travelapi.com/hotels/24000000/23720000/23711100/23711069/cc43d4f2_z.jpg'}}}], 'bed_groups': {'37378': {'id': '37378', 'description': '3 King Beds', 'configuration': [{'quantity': 3, 'size': 'King', 'type': 'KingBed'}]}}}}, 'rates': {'264015946': {'id': '264015946'}, '264015947': {'id': '264015947'}}, 'dates': {'added': '2018-04-08T13:51:18.663Z', 'updated': '2019-09-20T19:46:10.952Z'}, 'descriptions': {'amenities': "Don't miss out on recreational opportunities including an outdoor pool and a fitness center.", 'business_amenities': 'Free self parking is available onsite.', 'rooms': 'Make yourself comfortable in this air-conditioned apartment, featuring a kitchen with a refrigerator and a stovetop. An LED television with cable programming provides entertainment, while complimentary wireless Internet access keeps you connected. Conveniences include a microwave and an electric kettle, and housekeeping is provided once per stay.', 'attractions': 'Distances are displayed to the nearest 0.1 mile and kilometer. <br /> <p>Dubai Marina - 0.1 km / 0.1 mi <br /> The Walk - 0.1 km / 0.1 mi <br /> Jumeirah Beach - 0.5 km / 0.3 mi <br /> The Beach Mall - 0.8 km / 0.5 mi <br /> Dubai Marina Mall - 1.9 km / 1.2 mi <br /> Ain Dubai - 1.9 km / 1.2 mi <br /> Skydive Dubai - 3.1 km / 1.9 mi <br /> Bluewaters Island - 4.3 km / 2.7 mi <br /> American University of Dubai (AUD) - 4.5 km / 2.8 mi <br /> Ibn Battuta Mall - 5 km / 3.1 mi <br /> Dubai College - 6.5 km / 4 mi <br /> Jebel Ali Race Course - 8.3 km / 5.2 mi <br /> Emirates Golf Club - 8.5 km / 5.3 mi <br /> Al Sufouh Beach - 11.2 km / 7 mi <br /> Fatima Abdullah Mohammed Rasheed Mosque - 11.4 km / 7.1 mi <br /> </p><p>The nearest airports are:<br />Dubai (DWC-Al Maktoum Intl.) - 35.8 km / 22.3 mi<br /> Dubai (DXB-Dubai Intl.) - 36 km / 22.4 mi<br /> Sharjah (SHJ-Sharjah Intl.) - 62.8 km / 39 mi<br /> </p><p></p>', 'location': "With a stay at this apartment in Dubai (Jumeirah Beach Residence), you'll be steps from Dubai Marina and The Walk.  This apartment is 0.3 mi (0.5 km) from Jumeirah Beach and 1.7 mi (2.8 km) from Dubai Marina Mall.", 'headline': 'Near The Walk'}, 'themes': {'2333': {'id': 2333, 'name': 'Family property'}}, 'statistics': {'52': {'id': 52, 'name': 'Total number of rooms - 1', 'value': '1'}}}

print(dic["checkin"]["begin_time"])
print(dic["checkin"]["instructions"])
print(dic["checkout"]["time"])

print(dic.get("checkin").get("end_time") or None)


None
